### ISSUE TITLE
migrate from Jeweler to Bundler

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonifi#1]
Needs to be done to simplify travis, and modernize.

**Comment by LocoDelAssembly** [comment]
Looks solved by https://github.com/SpeciesFileGroup/taxonifi/commit/175661f61bf223e7a652bc47298db69f20ed9d2e and https://github.com/SpeciesFileGroup/taxonifi/commit/f97331f0a8119ae81577be576163c3fe53ac2775
